### ISSUE TITLE
docker container gives errors when run from singularity

### ISSUE THREAD

**Issue by cboursnell** [cancerit/BRASS#92]
I am trying to use the docker image from quay.io/wtsicgp/brass on our hpc. I have run
`singularity build --remote brass.sif docker://quay.io/wtsicgp/brass:v6.3.0`
and then
`singularity exec brass.sif brass.pl`
I get this error message: 
`
IPC::System::Simple required for Fatalised/autodying system() at /opt/wtsi-cgp/bin/brass.pl line 40.
        main::BEGIN() called at /opt/wtsi-cgp/bin/brass.pl line 40
        eval {...} called at /opt/wtsi-cgp/bin/brass.pl line 40
BEGIN failed--compilation aborted at /opt/wtsi-cgp/bin/brass.pl line 40.
`
There is little information in the README or on the wiki about running brass with the docker image. 
Could you help with fixing this please?

**Comment by keiranmraine** [comment]
Under singularity use `--cleanenv` otherwise it passes in the wrapping environment and clobbers the ones set within the container.

I reported this issue to singularity and it appears a fix for this is either released or soon to be:

https://github.com/sylabs/singularity/issues/3331#issuecomment-494519266
